version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IO.RecyclableMemoryStream
    versions:
    - 1.4.1
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
